export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_ALL_TEMPERAMENTS ="GET_ALL_TEMPERAMENTS";
export const POST_NEWBREED = "POST_NEWBREED";
export const GET_BY_NAME = "GET_BY_NAME";
export const ORDER_BREEDS = "ORDER_BREEDS";
export const CLEAR_STATE = "CLEAR_STATE";
export const GET_BY_DETAIL = "GET_BY_DETAIL";
