export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_ALL_TEMPERAMENTS ="GET_ALL_TEMPERAMENTS";
export const POST_NEWBREED = "POST_NEWBREED";
export const FILTER_BREEDS = "FILTER_BREEDS";
export const ORDER_BREEDS = "ORDER_BREEDS";